language: go

go:
  - "1.12.x"

env:
  - GO111MODULE=on

install: true

after_script:
  - go get -v github.com/alecthomas/gometalinter/...
  - gometalinter --install
  - gometalinter

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
  
  
deploy:
  provider: releases
  api_key: ${api_key}
  file: "supervisord"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
